""" Implement the hello command.

"""
import csv
import sys

from datetime import datetime
from uuid import uuid4
from shutil import copy
from pathlib import Path
from guano import GuanoFile
from ..core.logger import logger


def main(wav_dir, input_file) -> str:
    """ Execute the command.

    :param wav_dir: the directory where wav files are stored
    :param input_file: the full path of the csv input file generated by 'readwav'
    """
    logger.debug("executing hello command")

    try:
        backup_dir = Path(wav_dir[0]).joinpath('guanoctl_out')
    except FileNotFoundError:
        logger.error('The wav directory does not exist!')
        sys.exit()

    try:
        backup_dir.mkdir()
    except FileExistsError:
        logger.error('The working directory already exists.')
        sys.exit()

    for file in Path(wav_dir[0]).glob('*.[Ww][Aa][Vv]'):
        copy(file.as_posix(), backup_dir.as_posix())






    return "Hello"  # TODO: use f-string for Python 3.6+
